---

name: CI macOS (Homebrew)

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: CI on macOS (Homebrew)

    runs-on: macos-12

    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: alire-project/setup-alire
      uses: alire-project/setup-alire@v3
    -
      name: Install toolchain
      run: |
        alr --non-interactive settings --global --set toolchain.assistant false
        alr --non-interactive toolchain --select gnat_native
        alr --non-interactive toolchain --select gprbuild
    -
      name: Install SDL2 components
      run: |
        brew install sdl2
        brew install sdl2_image
        brew install sdl2_mixer
        brew install sdl2_ttf
    -
      name: Build and run
      run: |
        eval $(brew shellenv)
        export C_INCLUDE_PATH=$HOMEBREW_PREFIX/include
        export CPP_INCLUDE_PATH=$HOMEBREW_PREFIX/include
        export LIBRARY_PATH=$HOMEBREW_PREFIX/lib
        alr --non-interactive build
