---

name: CI macOS (Frameworks)

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: CI on macOS (Frameworks)

    runs-on: macos-12

    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: alire-project/setup-alire
      uses: alire-project/setup-alire@v3
    -
      name: Install toolchain
      run: |
        alr --non-interactive settings --global --set toolchain.assistant false
        alr --non-interactive toolchain --select gnat_native
        alr --non-interactive toolchain --select gprbuild
    -
      name: Disable Homebrew
      run: rm -f $(which brew)
      shell: bash
    -
      name: Install SDL2.framework
      run: |
        curl -LJ -v https://github.com/libsdl-org/SDL/releases/download/release-2.30.3/SDL2-2.30.3.dmg --output ~/tmp/SDL2.dmg
        hdiutil attach -mountpoint ~/tmp/SDL2 ~/tmp/SDL2.dmg
        cp -pR ~/tmp/SDL2/SDL2.framework /Library/Frameworks
      shell: bash
    -
      name: Build and run
      run: |
        alr --non-interactive build
